apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mealops-prod

resources:
- ../../base

images:
- name: mealops
  newName: mealopsacr12345.azurecr.io/mealops
  newTag: 5cb249e143c79fd75e9554ff21dc15e7e078fe3d
