apiVersion: apps/v1
kind: Deployment

metadata:
  name: mealops-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mealops-app

  template:
    metadata:
      labels:
        app: mealops-app

    spec:
      containers:
        - name: mealops-app
          image: mealopsacr12345.azurecr.io/mealops:v1
          ports:
            - containerPort: 8000
